---
- name: Update Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Install wget using Homebrew
      become: false
      community.general.homebrew:
        name: dockutil
        state: present
