---
- name: Update Software
  hosts: localhost
  gather_facts: false

  vars:
    dockutil_install: true
    dockitems_remove:
      - Launchpad
      - Messages

  roles:
    - name: geerlingguy.mac.dock
    - name: geerlingguy.mac.homebrew
