---
- name: Configure macOS Dock
  hosts: localhost
  become: true

  vars:
    dockitems_remove:
      - Launchpad
      - Messages
      - Maps
      - Photos
  
  pre_tasks:
    - name: Ensure dockutil is installed
      become: false
      homebrew:
        name: dockutil
        state: present

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.dock
