---
- name: Update Software
  hosts: localhost

  vars:
    dockitems_remove:
      - Launchpad
      - Messages
    homebrew_installed_packages:
      - wget
    mas_installed_apps:
      - { id: 424389933, name: "Final Cut Pro" }

  pre_tasks:
    - name: Ensure dockutil is installed
      become: false
      community.general.homebrew:
        name: dockutil
        state: present

  roles:
    - name: geerlingguy.mac.dock
    - name: geerlingguy.mac.homebrew
    - name: geerlingguy.mac.mas
