---
- name: Update Software
  hosts: localhost

  vars:
    dockitems_remove:
      - Launchpad
      - Messages

  pre_tasks:
    - name: Ensure dockutil is installed
      become: false
      community.general.homebrew:
        name: dockutil
        state: present

  roles:
    - name: geerlingguy.mac.dock
    - name: geerlingguy.mac.homebrew
    - name: geerlingguy.mac.mas
