---
- name: Update Software
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: dockutil is installed
      become: false
      community.general.homebrew:
        name: dockutil
        state: present
